name: 💡 Feature Request
description: Suggest a new optimization, tweak, or improvement for PMan.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Got an idea to squeeze more performance out of Windows?**
        Let us know!
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests.
          required: true
        - label: This request focuses on a single feature or optimization concept.
          required: true
  - type: input
    id: version
    attributes:
      label: Current Version
      placeholder: v1.x.x
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm frustrated when PMan doesn't automatically detect my custom launcher for..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: Describe the solution you'd like. A new registry tweak? A UI change? New affinity logic?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
    validations:
      required: false
