#ifndef VERSION_H
#define VERSION_H

#define PMAN_VERSION_MAJOR 2
#define PMAN_VERSION_MINOR 3
#define PMAN_VERSION_PATCH 0
#define PMAN_VERSION_BUILD 2026

// Helper macros to turn numbers into strings
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define PMAN_FVERSION_STRING STRINGIZE(PMAN_VERSION_MAJOR) "." \
                            STRINGIZE(PMAN_VERSION_MINOR) "." \
                            STRINGIZE(PMAN_VERSION_PATCH)
#define PMAN_PVERSION_STRING STRINGIZE(PMAN_VERSION_MAJOR) "."

#define PMAN_FILE_VERSION_STRING PMAN_FVERSION_STRING "." STRINGIZE(PMAN_VERSION_BUILD)
#define PMAN_PRODUCT_VERSION_STRING PMAN_PVERSION_STRING "." STRINGIZE(PMAN_VERSION_BUILD)
#endif // VERSION_H
